version: '3.1'

networks:
  aiohttp_network:

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: aiohttp_db_user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: aiohttp_homework
    networks:
      aiohttp_network:
        aliases:
          - database
    ports:
      - 5430:5432

  app:
    depends_on:
      - db
    image: aiohttp_homework
    build:
      dockerfile: Dockerfile
    command: gunicorn aiohttp_homework.main:my_app -b 0.0.0.0:8080 --worker-class aiohttp.GunicornWebWorker
    networks:
      aiohttp_network:
        aliases:
          - my_app
    ports:
      - 8080:8080
